name: Build and Deploy to Store

on:
  push:
    branches:
      - release/*
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build'
        required: false
        default: ''

permissions:
  contents: write
  actions: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  store:
    needs: build
    uses: ./.github/workflows/store-upload.yml
    secrets: inherit
  version:
    needs: store
    uses: ./.github/workflows/gittag.yml
  release:
    needs: store
    uses: ./.github/workflows/log.yml
    with:
      username: 'Henrietta the Whale'
      avatar_url: 'https://github.com/Leisvan/Ascendia/blob/main/.assets/AvatarLogo.png?raw=true'
      thumbnail_url: 'https://github.com/Leisvan/Ascendia/blob/main/.assets/Ascendia.Logo.png?raw=true'
    secrets: inherit